# Generated by Django 3.2.3 on 2021-06-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[('4', 'Low'), ('3', 'Medium'), ('2', 'High'), ('1', 'Urgent')], default='4'),
        ),
    ]
