# Generated by Django 3.2.3 on 2021-06-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=4, verbose_name=[(4, 'Low'), (3, 'Medium'), (2, 'High'), (1, 'Urgent')]),
        ),
    ]
